#######################################################################
# title:    2.9 - Using Dependabot for Provider Version Updates
# original: https://github.com/terraform-cookbook/recipes/tree/main/chapter-02/using-dependabot-for-provider-version-updates
#######################################################################

---

version: 2

updates:
  - package-ecosystem: "terraform"
    directory: "/"

    schedule:
      interval: "weekly"

    open-pull-requests-limit: 5

    allow:
      - dependency-type: "all"

    ignore:
      - dependency-name: "aws"
        versions: ["5.x"] # Example: ignore major version upgrades
