#######################################################################
# title:    6.4 - Using HCP Terraform with GitHub Actions
# original: https://github.com/terraform-cookbook/recipes/tree/main/chapter-06/using-hcp-terraform-with-github-actions
#######################################################################

---

name: "Terraform GitHub Actions"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    steps:
      # see https://github.com/actions/checkout/releases
      - name: Check out the repository
        uses: actions/checkout@v4

      # see https://github.com/hashicorp/setup-terraform/releases
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
        if: github.ref == 'refs/heads/main'
