#######################################################################
# title:    2.10 - Using GitHub Codespaces and DevContainers
# original: https://github.com/terraform-cookbook/recipes/tree/main/chapter-02/using-github-codespaces-and-devcontainers
#######################################################################

FROM hashicorp/terraform:latest

RUN apt-get update && apt-get install -y git
