#######################################################################
# title:    5.4 - Scheduling Containers on Kubernetes with YAML
# original: https://github.com/terraform-cookbook/recipes/tree/main/chapter-05/scheduling-containers-on-kubernetes-with-yaml
#######################################################################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: my-image:latest
          ports:
            - containerPort: 8080
